#ifndef _IGBTMODULETYPES_H_
#define _IGBTMODULETYPES_H_

// Defines
#define IGBT_CASE_MIAA			3010
#define IGBT_CASE_MDAA			3011
#define IGBT_CASE_MIA2			3012
#define IGBT_CASE_MDA2			3013

#define IGBT_CASE_MIDA			3020
#define IGBT_CASE_MDDA			3021
#define IGBT_CASE_MID2			3022
#define IGBT_CASE_MDD2			3023

#define IGBT_CASE_MIFA			3030
#define IGBT_CASE_MDFA			3031
#define IGBT_CASE_MIF2			3032
#define IGBT_CASE_MDF2			3033

#define IGBT_CASE_MIHA			3040
#define IGBT_CASE_MIH2			3041

#define IGBT_CASE_MIHM			3050
#define IGBT_CASE_CERT_MIHM		3051

#define IGBT_CASE_MIHV			3060

#define IGBT_CASE_MISM			3070
#define IGBT_CASE_MDSM			3071

#define IGBT_CASE_MISV			3080
#define IGBT_CASE_MDSV			3081

#define IGBT_CASE_MIXM			3090
#define IGBT_CASE_CERT_ADAP		3091

#define IGBT_CASE_MIXV			3100
#define IGBT_CASE_MIRA			3110

#define IGBT_SCHEME_SS			16
#define IGBT_SCHEME_SD			17
#define IGBT_SCHEME_HB			18
#define IGBT_SCHEME_LC			19
#define IGBT_SCHEME_HC			20
#define IGBT_SCHEME_DD			21
#define IGBT_SCHEME_DS			23
#define IGBT_SCHEME_CH			24
#define IGBT_SCHEME_LR_LRD		25
#define IGBT_SCHEME_CE			26

// Type
typedef enum __ModuleType
{
	Module_None,
	MDAA_DD = IGBT_CASE_MDAA * 100 + IGBT_SCHEME_DD,
	MDDA_DD = IGBT_CASE_MDDA * 100 + IGBT_SCHEME_DD,
	MDFA_DD = IGBT_CASE_MDFA * 100 + IGBT_SCHEME_DD,
	MDSM_SD = IGBT_CASE_MDSM * 100 + IGBT_SCHEME_SD,
	MDSV_SD = IGBT_CASE_MDSV * 100 + IGBT_SCHEME_SD,
	MIAA_CE = IGBT_CASE_MIAA * 100 + IGBT_SCHEME_CE,
	MIAA_HB = IGBT_CASE_MIAA * 100 + IGBT_SCHEME_HB,
	MIAA_HC = IGBT_CASE_MIAA * 100 + IGBT_SCHEME_HC,
	MIAA_LC = IGBT_CASE_MIAA * 100 + IGBT_SCHEME_LC,
	MIFA_HB = IGBT_CASE_MIFA * 100 + IGBT_SCHEME_HB,
	MIFA_HC = IGBT_CASE_MIFA * 100 + IGBT_SCHEME_HC,
	MIFA_LC = IGBT_CASE_MIFA * 100 + IGBT_SCHEME_LC,
	MIFA_SD = 1,
	MIDA_HB = IGBT_CASE_MIDA * 100 + IGBT_SCHEME_HB,
	MIHA_HB = IGBT_CASE_MIHA * 100 + IGBT_SCHEME_HB,
	MIHA_HC = IGBT_CASE_MIHA * 100 + IGBT_SCHEME_HC,
	MIHA_LC = IGBT_CASE_MIHA * 100 + IGBT_SCHEME_LC,
	MIHM_SS = IGBT_CASE_MIHM * 100 + IGBT_SCHEME_SS,
	MIHV_SS = IGBT_CASE_MIHV * 100 + IGBT_SCHEME_SS,
	MISM_CH = IGBT_CASE_MISM * 100 + IGBT_SCHEME_CH,
	MISM_DS = IGBT_CASE_MISM * 100 + IGBT_SCHEME_DS,
	MISM_SS = IGBT_CASE_MISM * 100 + IGBT_SCHEME_SS,
	MISV_SS = IGBT_CASE_MISV * 100 + IGBT_SCHEME_SS,
	MIXM_HB = IGBT_CASE_MIXM * 100 + IGBT_SCHEME_HB,
	MIXM_LR_LRD = IGBT_CASE_MIXM * 100 + IGBT_SCHEME_LR_LRD,
	MIXV_HB = IGBT_CASE_MIXV * 100 + IGBT_SCHEME_HB,
} ModuleTypes;


#endif /* _IGBTMODULETYPES_H_ */
